### ISSUE TITLE
wifiClientSecure.setCACert() is duplicated

### ISSUE THREAD

**Issue by igolubic** [iotaap/iotaap-os#5]
wifiClientSecure.setCACert() is duplicated, now it loads the same certificate (before it was loading MQTT and OTAu certificates separately).

This is maybe redundant since there can be only one wifiClientSecure but now we use the same certificate, this maybe can be removed?

Usage in ota_module.cpp:

https://github.com/iotaap/iotaap-os/blob/2d61943b79f46973b7092c9631eae79d5b77f2e7/src/ota/ota_module.cpp#L51
https://github.com/iotaap/iotaap-os/blob/2d61943b79f46973b7092c9631eae79d5b77f2e7/src/ota/ota_module.cpp#L95

Usage in mqtt_client.cpp:

https://github.com/iotaap/iotaap-os/blob/c7f25e4baecd3dd315aa99160b324582b8073ef3/src/mqtt/mqtt_client.cpp#L184

**Comment by alanroot73** [comment]
Per my view this can and should be optimized

**Comment by igolubic** [comment]
Fixed by: https://github.com/iotaap/iotaap-os/pull/13
