### ISSUE TITLE
ESP32 MQTT problem, subscribe broken

### ISSUE THREAD

**Issue by sunilkul1** [iotaap/iotaap-os#7]
If uploading the code, and not using sleep function, ESP32 subscribes and publishes to some topic succesfully (MQTT Broker is on Raspberry PI, all debugging is done in serial monitor).

Serial output:

```
WiFi connected
IP address: 
x
Boot number: 2
Setup ESP32 to sleep for every 5 Seconds
Attempting MQTT connection...connected
Subscribed to esp32/topic
Going to sleep now
ets Jun  8 2016 00:22:57
```

**Comment by igolubic** [comment]
This doesn't look like an issue with IoTaaP OS. Please provide more details

**Comment by sunilkul1** [comment]
This was the issue due to some local library. It's fixed now.
